# Generated by Django 3.0.6 on 2020-05-31 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_number', models.CharField(max_length=12)),
                ('name', models.CharField(max_length=128)),
                ('certification_date', models.DateField()),
                ('expiration_date', models.DateField()),
            ],
        ),
    ]
